metadata:
  managedFields:
    - apiVersion: v1
      fieldsType: Fieldsv1
      fieldsV1:
        f:data:
          .: {}
          f:tls.crt: {}
          f:tls.key: {}
        f:type: {}
      manager: kubectl
      operation: Update
      time: "2021-01-29T20:33:54Z"
    name: healthcheck-certs
    namespace: {{ .Values.namespace }}
type: kubernetes.io/tls
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: healthcheck
    name: healthcheck
    namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthcheck
      template:
        metadata:
          labels:
            app: healthcheck
        spec:
          containers:
          - image: {{ .Values.healthcheckDeployment.image }}:{{ .Values.healthcheckDeployment.tag }}
            name: healthcheck
            ports:
              - containerPort: 443
                name: healthcheck
          imagePullSecrets:
            - name: awssecret
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: healthcheck
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: http
      port: 443
      targetPort: 443
      protocol: TCP
  selector:
    app: healthcheck
