apiVersion: v1
kind: PersistantVolumeClaim
metadata:
  name: {{ .Values.dbDeployment.claimName }}
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    request:
      storage: 50Mi
