---
- name: Stop and Remove Previous Container
  ansible.builtin.shell: docker stop {{ MKDOCS_APP_NAME }} && docker rm {{ MKDOCS_APP_NAME }}
  register: docker_stop
  timeout: 30
  ignore_errors: yes
- debug: msg="{{ docker_stop.stdout_lines }}"

- name: Start New Container
  ansible.builtin.shell: docker run -d -p 8000:8000 --name {{ MKDOCS_APP_NAME }} {{ DOCKERHUB_ACCOUNT }}/{{ MKDOCS_APP_NAME }}:{{ APP_TAG }}
  register: start_container
  timeout: 180
- debug: msg="{{ start_container.stdout_lines }}"

- name: List Docker Processes
  ansible.builtin.shell: docker ps
  register: docker_processes
  timeout: 30
- debug: msg="{{ docker_processes.stdout_lines }}"
