---
- name: Create Node Exporter Group
  ansible.builtin.group:
    name: node_exporter
    state: present

- name: Create Node Exporter User
  ansible.builtin.user:
    name: node_exporter
    groups: node_exporter
    append: true
    shell: /usr/sbin/nologin
    system: true
    create_home: false
    home: /

- name: Download Node Exporter
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz"
    dest: "/tmp/node_exporter-1.7.0.linux-amd64.tar.gz"
    mode: '0644'

- name: Decompress archive
  become: true
  ansible.builtin.unarchive:
    src: "/tmp/node_exporter-1.7.0.linux-amd64.tar.gz"
    dest: "/tmp"
    creates: "/tmp/node_exporter-1.7.0.linux-amd64/node_exporter"
    remote_src: true

- name: Move binary to path
  become: true
  ansible.builtin.copy:
    src: "/tmp/node_exporter-1.7.0.linux-amd64/node_exporter"
    dest: "/usr/local/bin/node_exporter"
    mode: 0755
    owner: root
    group: root
    remote_src: true

- name: Cleanup
  become: true
  ansible.builtin.shell: rm -r /tmp/node_exporter-1.7.0.linux-amd64*
