---
- name: Stop and Remove Previous Container
  ansible.builtin.shell: docker stop prometheus && docker rm prometheus
  register: docker_stop
  timeout: 30
  ignore_errors: yes
- debug: msg="{{ docker_stop.stdout_lines }}"

- name: Create directory to put files into
  ansible.builtin.file:
    path: '/home/{{ ansible_user }}/.prometheus/'
    state: directory
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '0755'

- name: Update Prometheus Configuration
  ansible.builtin.template:
    src: 'prometheus.yml'
    dest: '/home/{{ansible_user}}/.prometheus/'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '0644'
    force: yes

- name: Create Docker Network
  ansible.builtin.shell: docker network create grafana-prometheus
  register: create_network
  timeout: 30
  ignore_errors: yes
- debug: msg="{{ create_network.stdout_lines }}"

- name: Start New Container
  ansible.builtin.shell:
    cmd: |
      docker run -d -p 9090:9090 \
        --name prometheus \
        --volume /home/{{ansible_user}}/.prometheus/prometheus.yml:/etc/prometheus/prometheus.yml \
        --network grafana-prometheus \
        --entrypoint /bin/prometheus \
        prom/prometheus:{{ PROM_TAG }} \
        --config.file=/etc/prometheus/prometheus.yml \
        --storage.tsdb.path=/prometheus \
        --web.console.libraries=/usr/share/prometheus/console_libraries \
        --web.console.templates=/usr/share/prometheus/consoles
  register: start_container
  timeout: 180
- debug: msg="{{ start_container.stdout_lines }}"

- name: List Docker Processes
  ansible.builtin.shell: docker ps
  register: docker_processes
  timeout: 30
- debug: msg="{{ docker_processes.stdout_lines }}"
