name: Docker Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build, tag, and push image to Dockerhub
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t docker.io/${{ vars.DOCKERHUB_ACCOUNT }}/${{ vars.DOCKERHUB_REPO }}:$IMAGE_TAG ./image
          docker push docker.io/${{ vars.DOCKERHUB_ACCOUNT }}/${{ vars.DOCKERHUB_REPO }}:$IMAGE_TAG

  deployment:
    name: Deploy
    needs: [ build ]
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v1
      - name: Deploy
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          ./scripts/update-docker-image.sh
